import path from 'path';
import { homedir } from 'os';
import { existsSync, readFileSync, writeFileSync, mkdirSync, chmodSync, rmSync } from 'fs';
import { execSync } from 'child_process';
import { logger } from '../../utils/logger.js';
import { injectContextIntoMarkdownFile } from '../../utils/context-injection.js';
import { KIMI_VSCODE_SCHEMA } from './KimiVscodeNormalizer.js';
import {
  DEFAULT_CONFIG_PATH,
  DEFAULT_STATE_PATH,
} from '../transcripts/config.js';
import type { TranscriptWatchConfig, WatchTarget } from '../transcripts/types.js';

// ─── Constants ───────────────────────────────────────────────────────────────

const KIMI_DIR           = path.join(homedir(), '.kimi');
const KIMI_MD_PATH       = path.join(KIMI_DIR, 'KIMI.md');
const KIMI_MEM_BIN_DIR   = path.join(homedir(), '.kimi-mem', 'bin');
const KIMI_WRAPPER_PATH  = path.join(KIMI_MEM_BIN_DIR, 'kimi');
const CLAUDE_MEM_DIR     = path.join(homedir(), '.claude-mem');
const KIMI_SIDECAR_DIR   = path.join(CLAUDE_MEM_DIR, 'kimi-vscode-transcripts');

export const KIMI_WATCH_NAME = 'kimi-vscode';

// ─── Wrapper script ───────────────────────────────────────────────────────────

export function buildKimiWrapperScript(realKimiPath: string): string {
  return `#!/usr/bin/env bash
# claude-mem Kimi wrapper — auto-generated by \`npx claude-mem install --ide kimi\`
# Do not edit manually — re-run install to regenerate.
REAL_KIMI="${realKimiPath}"
export KIMI_BASE_URL="http://localhost:11451/v1"
export KIMI_CWD="$(pwd)"

if [ -x "$REAL_KIMI" ]; then
  exec "$REAL_KIMI" "$@"
else
  echo "[claude-mem] kimi binary not found at $REAL_KIMI — set KIMI_BASE_URL manually" >&2
  exit 1
fi
`;
}

function findRealKimiBinary(): string {
  try {
    const result = execSync('which kimi', { encoding: 'utf-8', stdio: 'pipe' }).trim();
    if (result && result !== KIMI_WRAPPER_PATH) return result;
  } catch { /* kimi not in PATH */ }
  return '';
}

function installWrapperScript(realKimiPath: string): void {
  mkdirSync(KIMI_MEM_BIN_DIR, { recursive: true });
  const script = buildKimiWrapperScript(realKimiPath || '/usr/local/bin/kimi');
  writeFileSync(KIMI_WRAPPER_PATH, script, 'utf-8');
  chmodSync(KIMI_WRAPPER_PATH, 0o755);
}

function patchShellRc(rcPath: string): void {
  if (!existsSync(rcPath)) return;
  const content = readFileSync(rcPath, 'utf-8');
  const pathEntry = `export PATH="${KIMI_MEM_BIN_DIR}:$PATH"`;
  if (content.includes(KIMI_MEM_BIN_DIR)) return;
  writeFileSync(rcPath, content.trimEnd() + `\n\n# claude-mem Kimi wrapper\n${pathEntry}\n`, 'utf-8');
}

// ─── Transcript watch config ──────────────────────────────────────────────────

export function mergeKimiWatchConfig(
  existing: TranscriptWatchConfig,
  sidecarDir: string,
): TranscriptWatchConfig {
  const merged = { ...existing };

  // Add/replace kimi-vscode schema
  merged.schemas = { ...merged.schemas, 'kimi-vscode': KIMI_VSCODE_SCHEMA };

  const kimiWatch: WatchTarget = {
    name: KIMI_WATCH_NAME,
    path: path.join(sidecarDir, '**', '*.jsonl'),
    schema: 'kimi-vscode',
    startAtEnd: false,
    context: { mode: 'agents', updateOn: ['session_start', 'session_end'] },
  };

  const existingIdx = merged.watches.findIndex((w) => w.name === KIMI_WATCH_NAME);
  if (existingIdx >= 0) {
    const watches = [...merged.watches];
    watches[existingIdx] = kimiWatch;
    merged.watches = watches;
  } else {
    merged.watches = [...merged.watches, kimiWatch];
  }

  return merged;
}

function loadTranscriptConfig(): TranscriptWatchConfig {
  if (!existsSync(DEFAULT_CONFIG_PATH)) {
    return { version: 1, schemas: {}, watches: [], stateFile: DEFAULT_STATE_PATH };
  }
  try {
    const raw = readFileSync(DEFAULT_CONFIG_PATH, 'utf-8');
    const parsed = JSON.parse(raw) as TranscriptWatchConfig;
    if (!parsed.watches) parsed.watches = [];
    if (!parsed.schemas) parsed.schemas = {};
    if (!parsed.stateFile) parsed.stateFile = DEFAULT_STATE_PATH;
    return parsed;
  } catch {
    return { version: 1, schemas: {}, watches: [], stateFile: DEFAULT_STATE_PATH };
  }
}

function writeTranscriptConfig(config: TranscriptWatchConfig): void {
  mkdirSync(CLAUDE_MEM_DIR, { recursive: true });
  writeFileSync(DEFAULT_CONFIG_PATH, JSON.stringify(config, null, 2) + '\n', 'utf-8');
}

// ─── KIMI.md ─────────────────────────────────────────────────────────────────

function setupKimiMd(): void {
  const placeholder = `# Memory Context from Past Sessions

*No context yet. Complete your first Kimi session and context will appear here.*`;
  mkdirSync(KIMI_DIR, { recursive: true });
  // Only inject if the file doesn't already have a <claude-mem-context> block
  if (existsSync(KIMI_MD_PATH) && readFileSync(KIMI_MD_PATH, 'utf-8').includes('<claude-mem-context>')) return;
  injectContextIntoMarkdownFile(KIMI_MD_PATH, placeholder, '# Kimi Context');
}

// ─── Public API ───────────────────────────────────────────────────────────────

export async function installKimi(): Promise<number> {
  console.log('\nInstalling Claude-Mem Kimi integration...\n');
  let allOk = true;

  // Step 1: Wrapper (Lane B)
  try {
    const realKimi = findRealKimiBinary();
    installWrapperScript(realKimi);
    patchShellRc(path.join(homedir(), '.zshrc'));
    patchShellRc(path.join(homedir(), '.bashrc'));
    console.log(`  Wrapper installed: ${KIMI_WRAPPER_PATH}`);
    if (realKimi) {
      console.log(`  Real kimi binary: ${realKimi}`);
    } else {
      console.log(`  Note: kimi binary not found in PATH — set KIMI_BASE_URL manually`);
    }
  } catch (error) {
    console.error(`  Wrapper install failed: ${(error as Error).message}`);
    allOk = false;
  }

  // Step 2: Transcript watch config (Lane C)
  try {
    mkdirSync(KIMI_SIDECAR_DIR, { recursive: true });
    const config = loadTranscriptConfig();
    const merged = mergeKimiWatchConfig(config, KIMI_SIDECAR_DIR);
    writeTranscriptConfig(merged);
    console.log(`  VSCode transcript watch configured: ${DEFAULT_CONFIG_PATH}`);
    console.log(`  Sidecar directory: ${KIMI_SIDECAR_DIR}`);
  } catch (error) {
    console.error(`  Transcript config failed: ${(error as Error).message}`);
    allOk = false;
  }

  // Step 3: KIMI.md context placeholder
  try {
    setupKimiMd();
    console.log(`  KIMI.md placeholder: ${KIMI_MD_PATH}`);
  } catch (error) {
    console.error(`  KIMI.md setup failed: ${(error as Error).message}`);
    allOk = false;
  }

  console.log(`
Installation ${allOk ? 'complete' : 'partial'}!

Lane A (Proxy): Start the claude-mem worker to activate the proxy on port 11451.
  Set in your shell: export KIMI_BASE_URL="http://localhost:11451/v1"

Lane B (Wrapper): Restart your shell or run: source ~/.zshrc
  The \`kimi\` command will now route through the proxy automatically.

Lane C (VSCode): Restart the claude-mem worker to pick up the new transcript watch.

Context injection: ${KIMI_MD_PATH}
`);

  return allOk ? 0 : 1;
}

export function uninstallKimi(): number {
  console.log('\nUninstalling Claude-Mem Kimi integration...\n');

  // Remove wrapper
  if (existsSync(KIMI_WRAPPER_PATH)) {
    rmSync(KIMI_WRAPPER_PATH, { force: true });
    console.log(`  Removed wrapper: ${KIMI_WRAPPER_PATH}`);
  }

  // Remove kimi-vscode from transcript config
  if (existsSync(DEFAULT_CONFIG_PATH)) {
    const config = loadTranscriptConfig();
    config.watches = config.watches.filter((w) => w.name !== KIMI_WATCH_NAME);
    if (config.schemas) delete config.schemas['kimi-vscode'];
    writeTranscriptConfig(config);
    console.log(`  Removed kimi-vscode watch from ${DEFAULT_CONFIG_PATH}`);
  }

  // Remove claude-mem context from KIMI.md (preserve user content)
  if (existsSync(KIMI_MD_PATH)) {
    let content = readFileSync(KIMI_MD_PATH, 'utf-8');
    content = content.replace(/<claude-mem-context>[\s\S]*?<\/claude-mem-context>/g, '').trim();
    writeFileSync(KIMI_MD_PATH, content ? content + '\n' : '', 'utf-8');
    console.log(`  Removed context section from ${KIMI_MD_PATH}`);
  }

  console.log('\nUninstallation complete!\nRestart claude-mem worker and your shell to apply changes.\n');
  return 0;
}

export function checkKimiStatus(): number {
  console.log('\nClaude-Mem Kimi Integration Status\n');

  const wrapperInstalled = existsSync(KIMI_WRAPPER_PATH);
  console.log(`Wrapper (Lane B):  ${wrapperInstalled ? `Installed — ${KIMI_WRAPPER_PATH}` : 'Not installed'}`);

  const kimiMdExists = existsSync(KIMI_MD_PATH);
  const hasContext = kimiMdExists && readFileSync(KIMI_MD_PATH, 'utf-8').includes('<claude-mem-context>');
  console.log(`KIMI.md (Lane A):  ${hasContext ? `Active — ${KIMI_MD_PATH}` : kimiMdExists ? 'Exists, no context yet' : 'Not created'}`);

  if (existsSync(DEFAULT_CONFIG_PATH)) {
    const config = loadTranscriptConfig();
    const kimiWatch = config.watches.find((w) => w.name === KIMI_WATCH_NAME);
    console.log(`VSCode (Lane C):   ${kimiWatch ? `Configured — watching ${kimiWatch.path}` : 'Not configured'}`);
  } else {
    console.log(`VSCode (Lane C):   Not configured`);
  }

  console.log(`\nProxy (Lane A):    Start with: npx claude-mem start (port 11451)`);
  console.log('');
  return 0;
}

export async function handleKimiCommand(subcommand: string, _args: string[]): Promise<number> {
  switch (subcommand) {
    case 'install':   return installKimi();
    case 'uninstall': return uninstallKimi();
    case 'status':    return checkKimiStatus();
    default:
      console.log(`
Claude-Mem Kimi Integration

Usage: claude-mem kimi <command>

Commands:
  install     Install proxy wrapper, VSCode watcher, and KIMI.md placeholder
  uninstall   Remove Kimi integration (preserves user content)
  status      Check installation status

For docs: https://docs.claude-mem.ai/providers/kimi
      `);
      return 0;
  }
}
